In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,4],dtype= "int16")
print (a)

[1 2 4]


In [3]:
# get diminsion
a.ndim

1

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# get shape
b.shape

(2, 3)

In [6]:
# get type
a.dtype

dtype('int16')

In [8]:
#get size
a.itemsize

2

In [10]:
#get total bytes
a.nbytes

6